### ISSUE TITLE
Need a helpful warning if studio is imported but no initialized

### ISSUE THREAD

**Issue by AriaMinaei** [AriaMinaei/theatre#21]
Since tree-shaking in different build systems is not bullet proof, there are situations where the user intends for `@theatre/studio` to not be included in the bundle but it still ends up in there. We can help the user avoid this situation by emitting a warning if the studio is imported but `studio.initialize()` is not called within a time period.

**Comment by RuiOrey** [comment]
You're welcome @AriaMinaei !
Anyways, even if it is imported without being initialized, should it not impact the loading and play of sequences, right?
Seems there is some sort of code that is executed that breaks loading a json file and playing it.

**Comment by AriaMinaei** [comment]
Well if studio is present, all state loading is deferred to it. Otherwise, we'll have a situation where the state jumps from one that is provided to core, to one that studio has saved in localStorage.

**Comment by RuiOrey** [comment]
But should that only happen if we call `studio.initialize()` ?

**Comment by AriaMinaei** [comment]
I see what you mean. The word "initialize()" implies that, if not called, then it shouldn't affect anything. So `@theatre/core` would work as if `@theatre/studio` is not present.

My thinking is that `@theatre/studio` has no use if it isn't initialized. The reason I implemented `initialize()` was to give us a chance to [configure](https://github.com/AriaMinaei/theatre/blob/995dcd97aae256b9e7d603af9fdd5252683b8949/theatre/studio/src/TheatreStudio.ts#L151) the studio before it renders. So, if the studio is in the bundle but not initialized, then it's just taking up bundle space.

That's why I thought it's better to just warn the user if they're not calling `initialize()` right away.

**Comment by loklaan** [comment]
@AriaMinaei this looks to be [closed by this commit](https://github.com/theatre-js/theatre/commit/d6498585295962c55a6d412e74ad7f65af86adb7#diff-dbaec4167502b68fe66ce629dc407b3ad704643ab20c769560ee2c569cd9a7c5R148).

**Comment by OppositeX** [comment]
this issue is still an issue when using cdn with the old 0.5v
